### ISSUE TITLE
run failure

### ISSUE THREAD

**Issue by rooct** [Maxuss/chatgpt_rs#1]
example is failed

**Comment by Maxuss** [comment]
Can you specify the example?

**Comment by rooct** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，系统正在加紧处理中，不需额外提交，只需信息栏和反馈就行，请联系推荐人进行协助。

**Comment by NOBLES5E** [comment]
Check this https://github.com/transitive-bullshit/chatgpt-api#update-december-12-2022-

**Comment by Maxuss** [comment]
Fixed in #3
