### ISSUE TITLE
support more roles

### ISSUE THREAD

**Issue by octavei** [Maxuss/chatgpt_rs#5]
Great project! it would be perfect if more roles and moulde can be supported.

**Comment by octavei** [comment]
> Great project! it would be perfect if more roles and moulde can be supported.

You can refer to this project [https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V3.py](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V3.py)

**Comment by octavei** [comment]
You can also add proxy configuration

**Comment by Maxuss** [comment]
Alright, I'll look into it!

**Comment by octavei** [comment]
> Alright, I'll look into it!



> Alright, I'll look into it!

Grreat job!
