### ISSUE TITLE
Question: Is it possible to send a System message along with the normal one?

### ISSUE THREAD

**Issue by sanchopanca** [Maxuss/chatgpt_rs#55]
I see that there is a [variant](https://docs.rs/chatgpt_rs/latest/chatgpt/types/enum.Role.html#variant.System) of Role enum that looks like what I want, but how to actually send it?

**Comment by Maxuss** [comment]
This functionality will be added in the next update when function calling API #53 is finished ([here](https://github.com/Maxuss/chatgpt_rs/blob/function-calls/src/converse.rs#L97))
