### ISSUE TITLE
reply_count  vs max_tokens

### ISSUE THREAD

**Issue by hemeda3** [Maxuss/chatgpt_rs#59]
what is reply_count? if it suppose to mean openai official max_tokens term,  doesn't work for me, I was trying to use to restrict total token, but it seems not working,

I did some changes max_tokens based
https://platform.openai.com/docs/api-reference/completions
and seems working  
here is my ver simple changes:

https://github.com/Maxuss/chatgpt_rs/compare/master...hemeda3:chatgpt_rs:master

maybe I didn't know how to use it, feel free to close it if it's not an issue

**Comment by Maxuss** [comment]
`reply_count` controls the amount of individual message choices sent in the response. Feel free to open a PR to add `max_tokens` though!

**Comment by hemeda3** [comment]
@Maxuss thanks for replying, I have create a PR with test please check 

https://github.com/Maxuss/chatgpt_rs/pull/60
