### ISSUE TITLE
function calling response deserialization fails due to null content attribute

### ISSUE THREAD

**Issue by zaksamalik** [Maxuss/chatgpt_rs#65]
The [content](https://github.com/Maxuss/chatgpt_rs/blob/master/src/types.rs#L28) attribute of `ChatMessage` needs to be an optional string to support parsing `ChatMessage` responses with function calling.

```
"choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": null,
        "function_call": {
          "name": "<name>",
          "args": "<args>"
          }
          ...
```

**Comment by zaksamalik** [comment]
Alternatively could use `deserialize_with` and set an empty string

**Comment by Maxuss** [comment]
Should work fine in the latest release
