### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by fdietze** [Maxuss/chatgpt_rs#68]
Hi, I'd like to create a PR, but I don't know how to build locally. And there is no CI, which I can look at. I tried:

```
❯ cargo build
error: Package `chatgpt_rs v1.2.3 (/home/felix/projects/chatgpt_rs)` does not have feature `schemars`.
It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table,
so it does not have an implicit feature with that name.
```

What am I doing wrong?

**Comment by Maxuss** [comment]
What is your Rust version? Minimal supported Rust version for this project is 1.71.1

**Comment by fdietze** [comment]
Thank you. That was the problem. Mentioning this in the readme helps.

As a bonus, you could add a simple GitHub action, which compiles the code on every PR. I can help with this if needed.
