### ISSUE TITLE
No response in function calling example

### ISSUE THREAD

**Issue by raine** [Maxuss/chatgpt_rs#69]
```
% cargo run --example function_calls sk-xxx
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/function_calls sk-xxx`
Incoming message for maxus: This is a test message.
Response:
```

Is this the intended behavior?

edit: Great, I leaked my API key 😁, didn't notice it repeats in the output.

**Comment by Maxuss** [comment]
Yes, function call counts as a response. So if it succeeded, the response will be empty. Response will only be printed if the model fails to call (or decides not to call) a function for some reason.
